services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql_data:/var/lib/mysql

  studentbackend:
    image: studentbackend
    container_name: studentbackend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  studentfrontend:
    image: studentfrontend
    container_name: studentfrontend
    depends_on:
      studentbackend:
        condition: service_started
    ports:
      - "80:80"
